server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/course
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: ead-course-service
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

ead:
  api:
    url:
      authuser: 'http://localhost:8087'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost