version: '3.9'

services:
  course:
    container_name: ead-course-db
    image: postgres
    restart: always
    command: -p 5439
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: course
    volumes:
      - course-volume:/var/lib/postgresql
    networks:
      - course-network
    expose:
      - '5439'
    ports:
      - '5439:5439'

volumes:
  course-volume:

networks:
  course-network: